export const SALVAR_ACORDO_START = 'SALVAR_ACORDO_START';
export const SALVAR_ACORDO_COMPLETE = 'SALVAR_ACORDO_COMPLETE';
export const SALVAR_ACORDO_ERROR = `SALVAR_ACORDO_ERROR`;
export const BUSCAR_ACORDO_START = 'BUSCAR_ACORDO_START';
export const BUSCAR_ACORDO_COMPLETE = 'BUSCAR_ACORDO_COMPLETE';
export const BUSCAR_ACORDO_ERROR = `BUSCAR_ACORDO_ERROR`;