export const FORM_SUBMIT_FAIL = 'FORM_SUBMIT_FAIL';
export const FORM_SUBMIT_ERROR = 'FORM_SUBMIT_ERROR';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const UNAUTHORIZED = 'UNAUTHORIZED';

export const LOGIN_ERROR = 'LOGIN_ERROR';