export const COMPANY_MATCH_SEARCH_START = 'COMPANY_MATCH_SEARCH_START';
export const COMPANY_MATCH_SEARCH_COMPLETE = 'COMPANY_MATCH_SEARCH_COMPLETE';
export const COMPANY_MATCH_SEARCH_ERROR = 'COMPANY_MATCH_SEARCH_ERROR';