export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';
export const LOGOUT_COMPLETE = 'LOGOUT_COMPLETE';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const LOGIN_ERROR_UPDATE = 'LOGIN_ERROR_UPDATE';
