export const GET_CONFLITOS_COMPLETE = 'GET_CONFLITOS_COMPLETE';
export const GET_CONFLITOS_ERROR = 'GET_CONFLITOS_ERROR';
export const GET_ASSUNTOS_COMPLETE = 'GET_ASSUNTOS_COMPLETE';
export const GET_ASSUNTOS_ERROR = 'GET_ASSUNTOS_ERROR';
export const CLEAR_ASSUNTOS = 'CLEAR_ASSUNTOS';