export const BUSCAR_MEDIACAO_SITUACAO_START = 'BUSCAR_MEDIACAO_SITUACAO_START';
export const BUSCAR_MEDIACAO_SITUACAO_COMPLETE = 'BUSCAR_MEDIACAO_SITUACAO_COMPLETE';
export const BUSCAR_MEDIACAO_SITUACAO_ERROR = 'BUSCAR_MEDIACAO_SITUACAO_ERROR';