export const FILL_USER_DATA = 'FILL_USER_DATA';
export const FILL_PROFILE_DATA = 'FILL_PROFILE_DATA';
export const CLEAR_REGISTER_DATA = 'CLEAR_REGISTER_DATA';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER';