export const BUSCAR_ANEXO_START = 'BUSCAR_ANEXO_START';
export const BUSCAR_ANEXO_COMPLETE = 'BUSCAR_ANEXO_COMPLETE';
export const BUSCAR_ANEXO_ERROR = `BUSCAR_ANEXO_ERROR`;
export const UPLOAD_FILE_SUCCESS = `UPLOAD_FILE_SUCCESS`;
export const UPLOAD_FILE_FAIL= `UPLOAD_FILE_FAIL`;
export const UPLOAD_FILE_START = 'UPLOAD_FILE_START';
export const UPLOAD_FILE_CLEAR = 'UPLOAD_FILE_CLEAR';