export const BUSCAR_EMPRESA = 'BUSCAR_EMPRESA';
export const EMPRESA = 'EMPRESA';
export const MOTIVO = 'MOTIVO';
export const CONFIRMACAO = 'CONFIRMACAO';
export const MINIMO_CARACTERES_500 = 'MINIMO_CARACTERES_500';
export const SELECIONAR_CONFLITO_E_ASSUNTO = 'SELECIONAR_CONFLITO_E_ASSUNTO';
export const MAXIMO_CARACTERES_3000 = 'MAXIMO_CARACTERES_3000';