export const SAVE_MEDIATION_START = 'SAVE_MEDIATION_START';
export const SAVE_MEDIATION_COMPLETE = 'SAVE_MEDIATION_COMPLETE';
export const SAVE_MEDIATION_ERROR = 'SAVE_MEDIATION_ERROR';
export const CLEAR_MEDIATION_STATE = 'CLEAR_MEDIATION_STATE';