export const REMOVER_NEGOCIADOR_ERROR = 'REMOVER_NEGOCIADOR_ERROR';
export const REMOVER_NEGOCIADOR_COMPLETE = 'REMOVER_NEGOCIADOR_COMPLETE';
export const ADICIONAR_NEGOCIADOR_ERROR = 'ADICIONAR_NEGOCIADOR_ERROR';
export const ADICIONAR_NEGOCIADOR_COMPLETE = 'ADICIONAR_NEGOCIADOR_COMPLETE';