export const REMOVER_NEGOCIADOR_ERROR = 'REMOVER_NEGOCIADOR_ERROR';
export const REMOVER_NEGOCIADOR_COMPLETE = 'REMOVER_NEGOCIADOR_COMPLETE';
export const ADICIONAR_NEGOCIADOR_ERROR = 'ADICIONAR_NEGOCIADOR_ERROR';
export const ADICIONAR_NEGOCIADOR_COMPLETE = 'ADICIONAR_NEGOCIADOR_COMPLETE';
export const ADQUIRIR_NEGOCIADORES_COMPLETE = 'ADQUIRIR_NEGOCIADORES_COMPLETE';
export const ADQUIRIR_NEGOCIADORES_ERROR = 'ADQUIRIR_NEGOCIADORES_ERROR';
export const CARREGANDO = 'CARREGANDO';