export const GET_CONFIGURACAO_ERROR = 'GET_CONFIGURACAO_ERROR';
export const GET_CONFIGURACAO = 'GET_USERS_ERROR';
export const GET_CONFLITOS_ERROR = 'GET_CONFLITOS_ERROR';
export const GET_CONFLITOS = 'GET_CONFLITOS';
