export const GET_CONFIGURACAO_ERROR = 'GET_CONFIGURACAO_ERROR';
export const GET_CONFIGURACAO = 'GET_USERS_ERROR';
export const GET_CONFLITOS_ERROR = 'GET_CONFLITOS_ERROR';
export const GET_CONFLITOS = 'GET_CONFLITOS';
export const GET_CONFIGURACAO_CONFLITOS = 'GET_CONFIGURACAO_CONFLITOS';
export const GET_CONFIGURACAO_CONFLITOS_ERROR = 'GET_CONFIGURACAO_CONFLITOS_ERROR';
export const GET_CONFIGURACAO_ASSUNTOS = 'GET_CONFIGURACAO_ASSUNTOS';
export const GET_CONFIGURACAO_ASSUNTOS_ERROR = 'GET_CONFIGURACAO_ASSUNTOS_ERROR';
