export const PROFILE_COMPLETE = 'PROFILE_COMPLETE';
export const CARREGANDO = `CARREGANDO`;
export const ALTERACAO_SUCESSO = 'ALTERACAO_SUCESSO';
export const ALTERACAO_ERRO = `ALTERACAO_ERRO`; 
export const CLOSE_NOTIFICATION  = 'CLOSE_NOTIFICATION';
export const OPEN_NOTIFICATION  = 'OPEN_NOTIFICATION';
export const CARREGANDO_FINISH  = 'CARREGANDO_FINISH';
