export const BUSCAR_MEDIACAO_START = 'BUSCAR_MEDIACAO_START';
export const BUSCAR_MEDIACAO_COMPLETE = 'BUSCAR_MEDIACAO_COMPLETE';
export const BUSCAR_MEDIACAO_ERROR = 'BUSCAR_MEDIACAO_ERROR';
export const BUSCAR_MENSAGEM_START = 'BUSCAR_MENSAGEM_START';
export const BUSCAR_MENSAGEM_COMPLETE = 'BUSCAR_MENSAGEM_COMPLETE';
export const BUSCAR_MENSAGEM_ERROR = 'BUSCAR_MENSAGEM_ERROR';
export const LIMPAR_DADOS_MENSAGEM = `LIMPAR_DADOS_MENSAGEM`;